version: '3'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - './src/:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    hostname: mvc.loc
    volumes:
      - './src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
